---
matrix:
  include:
    - IMAGE: 3.8-buster
      TOXENV: lint
    - IMAGE: 3.8-buster
      TOXENV: sort
    - IMAGE: 3.8-buster
      TOXENV: format

pipeline:
  build:
    image: python:${IMAGE}
    commands:
      - apt update && apt install -y libgirepository1.0-dev
      - pip install tox
      - tox -e ${TOXENV}
